# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AddNode(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, hostname: str=None, ip: str=None, password: str=None, location: str=None, node_type: str=None):  # noqa: E501
        """AddNode - a model defined in Swagger

        :param name: The name of this AddNode.  # noqa: E501
        :type name: str
        :param hostname: The hostname of this AddNode.  # noqa: E501
        :type hostname: str
        :param ip: The ip of this AddNode.  # noqa: E501
        :type ip: str
        :param password: The password of this AddNode.  # noqa: E501
        :type password: str
        :param location: The location of this AddNode.  # noqa: E501
        :type location: str
        :param node_type: The node_type of this AddNode.  # noqa: E501
        :type node_type: str
        """
        self.swagger_types = {
            'name': str,
            'hostname': str,
            'ip': str,
            'password': str,
            'location': str,
            'node_type': str
        }

        self.attribute_map = {
            'name': 'name',
            'hostname': 'hostname',
            'ip': 'ip',
            'password': 'password',
            'location': 'location',
            'node_type': 'node_type'
        }
        self._name = name
        self._hostname = hostname
        self._ip = ip
        self._password = password
        self._location = location
        self._node_type = node_type

    @classmethod
    def from_dict(cls, dikt) -> 'AddNode':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The addNode of this AddNode.  # noqa: E501
        :rtype: AddNode
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this AddNode.


        :return: The name of this AddNode.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this AddNode.


        :param name: The name of this AddNode.
        :type name: str
        """

        self._name = name

    @property
    def hostname(self) -> str:
        """Gets the hostname of this AddNode.


        :return: The hostname of this AddNode.
        :rtype: str
        """
        return self._hostname

    @hostname.setter
    def hostname(self, hostname: str):
        """Sets the hostname of this AddNode.


        :param hostname: The hostname of this AddNode.
        :type hostname: str
        """

        self._hostname = hostname

    @property
    def ip(self) -> str:
        """Gets the ip of this AddNode.


        :return: The ip of this AddNode.
        :rtype: str
        """
        return self._ip

    @ip.setter
    def ip(self, ip: str):
        """Sets the ip of this AddNode.


        :param ip: The ip of this AddNode.
        :type ip: str
        """

        self._ip = ip

    @property
    def password(self) -> str:
        """Gets the password of this AddNode.


        :return: The password of this AddNode.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this AddNode.


        :param password: The password of this AddNode.
        :type password: str
        """

        self._password = password

    @property
    def location(self) -> str:
        """Gets the location of this AddNode.


        :return: The location of this AddNode.
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location: str):
        """Sets the location of this AddNode.


        :param location: The location of this AddNode.
        :type location: str
        """

        self._location = location

    @property
    def node_type(self) -> str:
        """Gets the node_type of this AddNode.


        :return: The node_type of this AddNode.
        :rtype: str
        """
        return self._node_type

    @node_type.setter
    def node_type(self, node_type: str):
        """Sets the node_type of this AddNode.


        :param node_type: The node_type of this AddNode.
        :type node_type: str
        """

        self._node_type = node_type
