# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ServiceFunctionNodeMigration(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, service_function_instance_name: str=None, destination_location: str=None):  # noqa: E501
        """ServiceFunctionNodeMigration - a model defined in Swagger

        :param service_function_instance_name: The service_function_instance_name of this ServiceFunctionNodeMigration.  # noqa: E501
        :type service_function_instance_name: str
        :param destination_location: The destination_location of this ServiceFunctionNodeMigration.  # noqa: E501
        :type destination_location: str
        """
        self.swagger_types = {
            'service_function_instance_name': str,
            'destination_location': str
        }

        self.attribute_map = {
            'service_function_instance_name': 'service_function_instance_name',
            'destination_location': 'destination_location'
        }
        self._service_function_instance_name = service_function_instance_name
        self._destination_location = destination_location

    @classmethod
    def from_dict(cls, dikt) -> 'ServiceFunctionNodeMigration':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The serviceFunctionNodeMigration of this ServiceFunctionNodeMigration.  # noqa: E501
        :rtype: ServiceFunctionNodeMigration
        """
        return util.deserialize_model(dikt, cls)

    @property
    def service_function_instance_name(self) -> str:
        """Gets the service_function_instance_name of this ServiceFunctionNodeMigration.


        :return: The service_function_instance_name of this ServiceFunctionNodeMigration.
        :rtype: str
        """
        return self._service_function_instance_name

    @service_function_instance_name.setter
    def service_function_instance_name(self, service_function_instance_name: str):
        """Sets the service_function_instance_name of this ServiceFunctionNodeMigration.


        :param service_function_instance_name: The service_function_instance_name of this ServiceFunctionNodeMigration.
        :type service_function_instance_name: str
        """

        self._service_function_instance_name = service_function_instance_name

    @property
    def destination_location(self) -> str:
        """Gets the destination_location of this ServiceFunctionNodeMigration.


        :return: The destination_location of this ServiceFunctionNodeMigration.
        :rtype: str
        """
        return self._destination_location

    @destination_location.setter
    def destination_location(self, destination_location: str):
        """Sets the destination_location of this ServiceFunctionNodeMigration.


        :param destination_location: The destination_location of this ServiceFunctionNodeMigration.
        :type destination_location: str
        """

        self._destination_location = destination_location